#Requires -Version 5.1
<#
.SYNOPSIS
  Rewrite Author/Committer on a branch: round-robin 4 Git handles, dates spread 2026-03-08 .. 2026-03-22 (see GIT_RESTRUCTURE_PLAN.md).

.DESCRIPTION
  The plan's 120+ narrative commits cannot be recreated from the current tree. This only rewrites existing commits (e.g. 21 on feature/junxiang-community-user).
  Uses git filter-branch (bash from Git for Windows).

.PARAMETER Apply
  Run filter-branch. Without it, DryRun only (prints mapping).

.PARAMETER Email*
  Four emails, or env GIT_TEAM_EMAIL_JUNXIANG, GIT_TEAM_EMAIL_SIYUAN, GIT_TEAM_EMAIL_JUNYI, GIT_TEAM_EMAIL_ALINA
#>
param(
  [string]$Branch = "feature/junxiang-community-user",
  [switch]$Apply,
  [string]$EmailJunxiang = $env:GIT_TEAM_EMAIL_JUNXIANG,
  [string]$EmailSiyuan = $env:GIT_TEAM_EMAIL_SIYUAN,
  [string]$EmailJunyi = $env:GIT_TEAM_EMAIL_JUNYI,
  [string]$EmailAlina = $env:GIT_TEAM_EMAIL_ALINA
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Convert-ToGitBashPath([string]$WindowsPath) {
  $p = $WindowsPath.TrimEnd('\')
  if ($p.Length -ge 2 -and $p[1] -eq ':') {
    $drive = $p.Substring(0, 1).ToLowerInvariant()
    $rest = $p.Substring(2).Replace('\', '/')
    return "/$drive$rest"
  }
  return $p.Replace('\', '/')
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$gitRoot = (Resolve-Path (Join-Path $scriptDir '..')).Path
Push-Location $gitRoot
$top = (git rev-parse --show-toplevel 2>$null).Trim()
if (-not $top) { throw "Not a git repository: $gitRoot" }

try {
  $bash = "${env:ProgramFiles}\Git\bin\bash.exe"
  if (-not (Test-Path -LiteralPath $bash)) {
    throw "Git Bash not found at $bash"
  }

  # Git handles match GIT_RESTRUCTURE_PLAN.md (Wang Junxiang, Wang Siyuan, Zhang Junyi, Zhang Liyin)
  $authors = @(
    @{ Git = "TJbubble"; Email = $EmailJunxiang }
    @{ Git = "siyuanWang348"; Email = $EmailSiyuan }
    @{ Git = "JunyiZ-hub"; Email = $EmailJunyi }
    @{ Git = "AlinaZLY"; Email = $EmailAlina }
  )

  $commits = @(git rev-list --reverse $Branch 2>$null)
  if ($commits.Count -eq 0) { throw "No commits on branch $Branch" }

  $start = [DateTimeOffset]::Parse("2026-03-08T10:15:00+08:00", [System.Globalization.CultureInfo]::InvariantCulture)
  $end = [DateTimeOffset]::Parse("2026-03-22T10:00:00+08:00", [System.Globalization.CultureInfo]::InvariantCulture)
  $ticksSpan = $end.Ticks - $start.Ticks
  $den = [Math]::Max(1, $commits.Count - 1)

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by apply-team-git-history.ps1 - do not commit")
  $lines.Add('case "$GIT_COMMIT" in')

  for ($i = 0; $i -lt $commits.Count; $i++) {
    $h = $commits[$i]
    $a = $authors[$i % 4]
    $t = $start.AddTicks([long]($ticksSpan * $i / $den))
    $dateStr = $t.ToString("yyyy-MM-dd HH:mm:ss", [System.Globalization.CultureInfo]::InvariantCulture) + " +0800"
    $subj = (git log -1 --format=%s $h).Trim()
    $displayEmail = if ($a.Email) { $a.Email } else { "(email not set)" }

    Write-Host ('{0} {1}  {2}  {3}' -f $h.Substring(0, 7), $a.Git, $displayEmail, $dateStr)
    Write-Host ('    {0}' -f $subj)

    $gitNameEsc = $a.Git -replace "'", "'\\''"
    $emailEsc = if ($a.Email) { ($a.Email -replace "'", "'\\''") } else { "" }
    $dateEsc = $dateStr -replace "'", "'\\''"

    $lines.Add('  ' + $h + ')')
    $lines.Add("    GIT_AUTHOR_NAME='$gitNameEsc'")
    $lines.Add("    GIT_AUTHOR_EMAIL='$emailEsc'")
    $lines.Add("    GIT_AUTHOR_DATE='$dateEsc'")
    $lines.Add('    ;;')
  }

  $lines.Add('  *) ;;')
  $lines.Add('esac')
  $lines.Add('export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"')
  $lines.Add('export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"')
  $lines.Add('export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"')

  if (-not $Apply) {
    Write-Host ""
    Write-Host "DryRun done. For real rewrite, set four GIT_TEAM_EMAIL_* env vars, then:" -ForegroundColor Yellow
    Write-Host '  .\scripts\apply-team-git-history.ps1 -Branch' $Branch '-Apply'
    return
  }

  foreach ($a in $authors) {
    if (-not $a.Email) { throw "Apply requires four emails (GIT_TEAM_EMAIL_* or parameters)." }
  }

  $envFile = Join-Path $gitRoot "scripts\.rewrite-env-generated.sh"
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($envFile, $lines, $utf8NoBom)

  $unixRoot = Convert-ToGitBashPath $gitRoot
  $unixEnv = Convert-ToGitBashPath $envFile

  $cmd = @"
set -e
cd '$unixRoot'
export FILTER_BRANCH_SQUELCH_WARNING=1
git filter-branch -f --env-filter ". '$unixEnv'" $Branch
"@
  & $bash -lc $cmd
}
finally {
  Pop-Location
}
